BUILD_DIR := build

CC := i686-elf-gcc
LD := i686-elf-ld
OBJCOPY := i686-elf-objcopy
AR := i686-elf-ar

CFLAGS := -ffreestanding -nostdlib -fno-pie -m32 -Wall -Wextra

CPPFLAGS := -I ./libc/include \
			-I ./stdlib/include

LIBC_LIB := $(BUILD_DIR)/libc.a
STDLIB_LIB := $(BUILD_DIR)/stdlib.a

HELLO_SRCS := ./programs/hello.c
HELLO_OBJS := $(HELLO_SRCS:%.c=$(BUILD_DIR)/%.o)
HELLO_ELF := $(BUILD_DIR)/hello.elf
HELLO_PROGRAM := $(BUILD_DIR)/hello.bin

LIBC_SRCS := \
		  ./libc/unistd/exit.c \
		  ./libc/unistd/read.c \
		  ./libc/unistd/write.c \
		  ./libc/stdio/printf.c \
		  ./libc/stdio/fgets.c \
		  ./libc/string.c \
		  ./libc/ioctl.c \
		  ./libc/mmap.c \
		  ./libc/munmap.c

STDLIB_SRCS := \
		  ./stdlib/malloc.c \
		  ./stdlib/free.c

CRT_SRCS := \
		  ./crt/crt0.c

LIBC_OBJS := $(LIBC_SRCS:%.c=$(BUILD_DIR)/%.o)
STDLIB_OBJS := $(STDLIB_SRCS:%.c=$(BUILD_DIR)/%.o)
CRT_OBJS := $(CRT_SRCS:%.c=$(BUILD_DIR)/%.o)
C_OBJS := $(LIBC_OBJS) $(STDLIB_OBJS) $(CRT_OBJS)

.PHONY: all clean

all: $(C_OBJS) $(LIBC_LIB) $(STDLIB_LIB) $(HELLO_PROGRAM)

$(BUILD_DIR)/%.o: %.c
	mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

$(LIBC_LIB): $(LIBC_OBJS)
	$(AR) rcs $@ $^

$(STDLIB_LIB): $(STDLIB_OBJS)
	$(AR) rcs $@ $^

$(HELLO_PROGRAM): $(HELLO_SRCS) $(LIBC_LIB) $(STDLIB_LIB) $(CRT_OBJS)
	mkdir -p $(BUILD_DIR)/programs
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $(HELLO_SRCS) -o $(HELLO_OBJS)
	$(LD) -m elf_i386 -Ttext=0x00001000 -e _start $(CRT_OBJS) $(HELLO_OBJS) $(STDLIB_LIB) $(LIBC_LIB) -o $(HELLO_ELF)
	$(OBJCOPY) -O binary $(HELLO_ELF) $@

clean:
	rm -rf $(BUILD_DIR)
